#!/bin/bash
set -e

##############################################################################
# Static Homepage Generation Script
#
# This script generates a static index.html from WordPress for optimal performance.
# It should be called after deployments to ensure the static file reflects the latest changes.
##############################################################################

# Configuration
PROJECT_ROOT="/var/www/sunnyside247ac_com"
STATIC_HTML="${PROJECT_ROOT}/index.html"
TEMP_HTML="${STATIC_HTML}.tmp"
LOG_FILE="${PROJECT_ROOT}/logs/static-generation.log"
TIMESTAMP=$(date +'%Y-%m-%d %H:%M:%S')

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Create log directory if it doesn't exist
mkdir -p "$(dirname "$LOG_FILE")"

# Logging function
log() {
    echo -e "${GREEN}[$TIMESTAMP]${NC} $1" | tee -a "$LOG_FILE"
}

error() {
    echo -e "${RED}[ERROR]${NC} $1" | tee -a "$LOG_FILE"
    exit 1
}

warn() {
    echo -e "${YELLOW}[WARNING]${NC} $1" | tee -a "$LOG_FILE"
}

log "=== Starting static homepage generation ==="

# Change to project root
cd "$PROJECT_ROOT" || error "Cannot change to project root"

# Backup current static HTML if it exists
if [ -f "$STATIC_HTML" ]; then
    cp "$STATIC_HTML" "${STATIC_HTML}.backup.$(date +%s)"
    log "✓ Backed up existing static HTML"
fi

log "Generating static homepage using WP-CLI..."

# Method 1: Try WP-CLI first
GENERATION_SUCCESS=false

if command -v wp >/dev/null 2>&1; then
    log "Using WP-CLI to generate homepage..."

    # Use WP-CLI eval to generate the homepage
    if wp shell --allow-root --basic <<'EOF'
ob_start();
define('WP_USE_THEMES', true);
wp();
include_once(ABSPATH . WPINC . '/template-loader.php');
$html = ob_get_contents();
ob_end_clean();
file_put_contents('index.html.tmp', $html);
echo "Generated static homepage with " . strlen($html) . " bytes\n";
EOF
    then
        log "✓ WP-CLI method completed successfully"

        # Check if the temp file was created and has content
        if [ -f "$TEMP_HTML" ] && [ -s "$TEMP_HTML" ]; then
            log "✓ HTML file generated by WP-CLI"
            GENERATION_SUCCESS=true
        else
            warn "HTML file not created by WP-CLI"
        fi
    else
        warn "WP-CLI method failed"
    fi
else
    warn "WP-CLI not available"
fi

# Method 2: Fallback to HTTP method if WP-CLI failed
if [ "$GENERATION_SUCCESS" = false ]; then
    log "Using HTTP method to generate homepage..."

    HTTP_STATUS=$(curl -s -w "%{http_code}" \
        -H "Host: sunnyside247ac.com" \
        -H "User-Agent: Mozilla/5.0 (compatible; StaticGenerator/1.0)" \
        -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" \
        -H "Cache-Control: no-cache, no-store, must-revalidate" \
        -H "Pragma: no-cache" \
        -H "Expires: 0" \
        -L \
        "http://127.0.0.1/index.php" \
        -o "$TEMP_HTML")

    if [ "$HTTP_STATUS" != "200" ]; then
        error "HTTP method failed. HTTP Status: $HTTP_STATUS"
    fi

    log "✓ HTTP method completed successfully"
fi

# Verify the temp file was created and has content
if [ ! -f "$TEMP_HTML" ] || [ ! -s "$TEMP_HTML" ]; then
    error "HTML file was not created or is empty"
fi

log "✓ HTML file generated successfully"

# Check if the response looks like HTML (basic validation)
if ! grep -q "<!DOCTYPE html\|<html" "$TEMP_HTML"; then
    error "Response doesn't appear to be valid HTML"
fi

log "✓ HTML content validated"

# Move temp file to final location
mv "$TEMP_HTML" "$STATIC_HTML"
log "✓ Static homepage generated: $STATIC_HTML"

# Set proper ownership
chown www-data:www-data "$STATIC_HTML"
log "✓ Set correct ownership for static HTML"

# Set proper permissions
chmod 644 "$STATIC_HTML"
log "✓ Set correct permissions for static HTML"

# Get file size for logging
FILE_SIZE=$(stat -c%s "$STATIC_HTML" 2>/dev/null || echo "unknown")
log "✓ Static HTML file size: $FILE_SIZE bytes"

# Fix logo marquee JavaScript initialization in static HTML
log "Fixing logo marquee JavaScript initialization..."
# Fix the broken JavaScript condition first
sed -i 's|if (container // Start when DOM is ready// Start when DOM is ready container.children.length === 0) {|if (container \&\& container.children.length === 0) {|g' "$STATIC_HTML"

# Clean up excessive debugging in logo marquee JavaScript
log "Cleaning up debugging in logo marquee JavaScript..."

# Remove duplicate animate function debugging lines
sed -i '/console\.log("🎬 Logo marquee animate\(\) called/d' "$STATIC_HTML"

# Add back essential debugging only
sed -i '/function animate() {/a\
\t\t// Minimal debugging for mobile issues\
\t\tif (Math.abs(translateX) % 50 < 0.8) console.log("🎬 Marquee running - translateX:", translateX, "logos:", logoInstances.length);' "$STATIC_HTML"

# Add debugging to the logo cycling logic for mobile width detection
sed -i '/if (translateX < -actualLogoWidth) {/a\
\t\t\t// Mobile debugging for logo width issues\
\t\t\tconsole.log("🔄 Recycling logo - width:", actualLogoWidth, "screen:", window.innerWidth, "translateX:", translateX);' "$STATIC_HTML"

# Fix JavaScript syntax error and improve getActualLogoWidth function
log "Fixing JavaScript syntax error in logo marquee..."
# Fix the specific double closing brace issue
sed -i '/return fallbackWidth; \/\/ Mobile: 120px, Tablet: 140px, Desktop: 160px/,/^[[:space:]]*}[[:space:]]*$/ {
    /return fallbackWidth; \/\/ Mobile: 120px, Tablet: 140px, Desktop: 160px/!d
    /^[[:space:]]*}[[:space:]]*$/!d
    /return fallbackWidth; \/\/ Mobile: 120px, Tablet: 140px, Desktop: 160px/a\
	}
}' "$STATIC_HTML"

# Update the getActualLogoWidth function for better mobile responsiveness
sed -i '/function getActualLogoWidth() {/,/return fallbackWidth; \/\/ Mobile: 120px, Tablet: 140px, Desktop: 160px/c\
\t// Measure actual logo width with better mobile handling\
\tfunction getActualLogoWidth() {\
\t\tif (container.children.length > 0) {\
\t\t\tconst firstLogo = container.children[0];\
\t\t\tconst computedStyle = window.getComputedStyle(firstLogo);\
\t\t\tconst width = firstLogo.offsetWidth;\
\t\t\tconst marginLeft = parseInt(computedStyle.marginLeft) || 0;\
\t\t\tconst marginRight = parseInt(computedStyle.marginRight) || 0;\
\t\t\tconst actualWidth = width + marginLeft + marginRight;\
\t\t\tconsole.log("📏 Measured logo width:", actualWidth, "window.innerWidth:", window.innerWidth);\
\t\t\treturn actualWidth;\
\t\t}\
\t\t// Better fallback based on screen size\
\t\tconst fallbackWidth = window.innerWidth < 768 ? 120 : (window.innerWidth < 1024 ? 140 : 160);\
\t\tconsole.log("📏 Using fallback logo width:", fallbackWidth, "window.innerWidth:", window.innerWidth);\
\t\treturn fallbackWidth; // Mobile: 120px, Tablet: 140px, Desktop: 160px\
\t}' "$STATIC_HTML"

# Add immediate initialization for static HTML
sed -i '/\/\/ Start when DOM is ready/i\
\t\t// Start immediately for static HTML\
\t\tsetTimeout(function() {\
\t\t\tconsole.log("⏰ Static HTML timeout - container exists:", !!container, "children:", container ? container.children.length : "N/A");\
\t\t\tif (container \&\& container.children.length === 0) {\
\t\t\t\tconsole.log("📝 Calling initializeLogos() from timeout");\
\t\t\t\tinitializeLogos();\
\t\t\t}\
\t\t}, 100);\
' "$STATIC_HTML"

# Now update the asset hashes if the update script exists
ASSET_UPDATE_SCRIPT="${PROJECT_ROOT}/wp-content/themes/sunnysideac/scripts/update-static-assets.sh"
if [ -f "$ASSET_UPDATE_SCRIPT" ]; then
    log "Running asset hash update script..."
    bash "$ASSET_UPDATE_SCRIPT" || warn "Asset hash update script failed, but static HTML was generated"
fi

# Clear any remaining caches
log "Clearing web server caches..."

# Restart Caddy to ensure it picks up the new static file
systemctl reload caddy 2>/dev/null || warn "Could not reload Caddy"

# Flush Redis cache (in case it's caching the old version)
redis-cli FLUSHALL 2>/dev/null || warn "Could not flush Redis cache"

log "=== Static homepage generation completed successfully ==="
log "The homepage is now available as: $STATIC_HTML"
log ""
log "To verify: curl -s https://sunnyside247ac.com | head -10"
log ""